### PR TITLE
Track truth monitoring80 x

### PR DESCRIPTION
**Pull request by smoortga**
Include possibility to monitor Track_truth variables (from TrackingParticles) alongside the normal reconstructed Track quantities using the TrackHistory Code

### CODE REVIEW

**Comment by ferencek** [comment]
This PR apparently breaks the code. I ran
```
cmsRun RecoBTag/PerformanceMeasurements/test/runBTagAnalyzer_cfg.py miniAOD=True maxEvents=100 reportEvery=1 wantSummary=False isReHLT=True usePuppi=True runFatJets=True runSubJets=True processStdAK4Jets=False usePuppiForBTagging=False
```
and this is what I get
```
----- Begin Fatal Exception 28-Nov-2016 16:46:42 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 3 event: 401
   [1] Running path 'p'
   [2] Calling event method for module BTagAnalyzer/'btaganaFatJets'
   [3] Calling produce method for unscheduled module QuickTrackAssociatorByHitsProducer/'quickTrackAssociatorByHits'
   [4] Calling produce method for unscheduled module ClusterTPAssociationProducer/'tpClusterProducer'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<TrackingParticle>
Looking for module label: mix
Looking for productInstanceName: MergedTrackTruth

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by ghost** [comment]
@smoortga do you have the possibility to check this? Thanks

**Comment by smoortga** [comment]
Hi @ferencek ,

Yes I think I know what is causing this.
could you maybe try and change the following three lines : https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/8_0_X/plugins/BTagAnalyzer.cc#L1684-L1686
to something like:

if (produceJetTrackTruthTree_){
  edm::Handle<ClusterTPAssociation> pCluster2TPListH;
  iEvent.getByToken(clusterTPMapToken_, pCluster2TPListH);
  const ClusterTPAssociation& clusterToTPMap = *pCluster2TPListH;
}

I forgot to include this protection, I'm sorry for the inconvenience.
If you can verify this solves the problem I will make a PR to include this protection.

Cheers
Seth

**Comment by ferencek** [comment]
@smoortga, this wouldn't work since `clusterToTPMap` is used later outside the if statement. I pushed changes https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/commit/6ea65411cf7cbe4b4661ad7f7c2946250544fe46 which I thought would solve the problem. However, for some unclear (at least to me) reason, this did not work. So I had to go with a more drastic measure in https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/commit/2cfb1fc7d7acde7105fa5958d6948f4cc28ad330.

So there seems to be something strange about the ClusterTPAssociationProducer which, when loaded, for some reason the framework attempts to run even when not other modules use its products as input.

**Comment by smoortga** [comment]
@ferencek,
Thank you very much for solving this! I agree that I also did not expect such a behavior ... Anyway if it works for you now that is good. Let me also try to run on a Recodebug sample with this option on when I arrive at work. To be sure everything runs as expected now.

Cheers 
Seth

**Comment by smoortga** [comment]
@ferencek 
Ok I can confirm it runs fine also on RECODEBUG with the option switched on now. I also saw you included your changes in 81X. Thanks again for handling this, I hope it was not too much of a nuisance.

Cheers
Seth

**Comment by ferencek** [comment]
I agree, since it works ok now, we can leave it like that. I would still like to understand why the framework attempts to run the ClusterTPAssociationProducer when it shouldn't but we can leave that for some other time ;)

**Pull request merged**
