### PR TITLE
Changes Daniel PhaseII backport to 94X

### PR DESCRIPTION
**Pull request by smoortga**
backport changes from https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/117 to branch 9_4_X_PhaseII

### CODE REVIEW

**Comment by rauser** [comment]
@smoortga thanks a lot! Are you sure about the default input file (https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/118/files#diff-5c146a2e7cd1cd5756fe360c41605498R13)

**Comment by smoortga** [comment]
@rauser No, but anyway it is commented out and it should be specified by the user. Nevertheless if you have a good example of a 94X PhaseII input file, I can include it. 
Should I perhaps restore the previous one that was there before:
	'inputFiles' : ['/store/mc/PhaseIIFall16DR82/TT_TuneCUETP8M1_14TeV-powheg-pythia8/AODSIM/PU200_90X_upgrade2023_realistic_v1-v1/110000/FCEB8448-98F6-E611-BA63-1866DAEB5D80.root',],
?

**Comment by rauser** [comment]
Ah sorry, I didn't realize it's commented. Then perhaps it doesn't matter and is good the way it is now. So anyone using it will be forced to think about which file to use.

**Comment by smoortga** [comment]
I agree, I will leave it as it is then. I am waiting for Daniels green light to merge the backport as well. Just to be sure nothing is missing.

Cheers!

**Comment by rauser** [comment]
Sounds good, thanks a lot!

**Pull request merged**
