### PR TITLE
[WIP] Adding DeepDoubleB input variables

### PR DESCRIPTION
**Pull request by jmduarte**
Work in progress [WIP].

This PR adds the DeepDoubleB input variables. Currently only adds features from first SV or track instance (to be discussed).

### CODE REVIEW

**Comment by mverzett** [comment]
@jmduarte I would wait to merge this PR. As you know @rauser made some extensive changes to the framework to lighten up the size of the output ntuples, this would create a lot of issues at merging. Any opinion on this @smoortga , @kskovpen @ferencek ?

@rauser when can we expect the slimming PR to be finalised?

**Comment by rauser** [comment]
Hi all,

I'll try to have it finalized by the end of the day, otherwise by tomorrow afternoon!

**Comment by ferencek** [comment]
This PR is mostly an example for how to extract the input features of the DeepDoubleB tagger and, as @jmduarte said, is work in progress. However, I do agree that any final PR should be made on top of @rauser's updated version.

**Comment by smoortga** [comment]
Exactly I agree as well, 
Given that @rauser will finalize things on a short timescale, this PR (with some possible modifications to match the updated BTA structure) can be integrated after that.

Thanks!

**Comment by rauser** [comment]
Hi all,

I finished the work yesterday and created the corresponding PR (https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/104). It is not merged yet, maybe @mverzett or @ferencek  could have a final look on it? My PR is on the 10_1_X branch, while the PR of @jmduarte is on 9_4_X. So in principal this PR could already be merged into 9_4_X, while some modifications are required to merge it into 10_1_X on top of my PR. If you want, I can take care of integrating the changes to 10_1_X.

Cheers

**Comment by rauser** [comment]
Hi all,
is this PR still alive? Or has it become obsolete after merging https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/116 ?
Best, Johann

**Comment by alefisico** [comment]
Hi, yes it become obsolete after #116 
thanks

**Comment by rauser** [comment]
Ok, thanks for reviewing this!

**Pull request closed without merging**
