### PR TITLE
track functionality for miniAOD

### PR DESCRIPTION
**Pull request by dmajumder**

### CODE REVIEW

**Comment by ghost** [comment]
@dmajumder it looks like test/BTagAnalyzerMacros/DrawCommPlot.C is being modified, with 1,533 additions, 1,471 deletions

**Comment by dmajumder** [comment]
Since plotting scripts were adapted to make some plots for boosted topologies.

**Comment by ghost** [comment]
@dmajumder this macro is used by several people and 3000 line changes seems quite a dramatic change, which is not connected to the purpose of the PR

**Comment by ferencek** [comment]
I agree with Ivan. It's better to leave the plotting macro updates for a separate PR. The changes are so many that GitHub refuses to display them so probably a better strategy would be to introduce separate plotting files for boosted topologies. Are all the changes completely transparent to the standard workflow for AK4 jets? 

I'm also adding @carolinecollard since she might have a preference on how to organize the plotting scripts.

**Comment by ferencek** [comment]
Btw, I don't want to be a pest, but is it really necessary to have so many merge commits. In this way the commit history gets unnecessarily very complicated (see https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/network). How about just cherry-picking 425b44a0b608b9aa3ba762c89d734c47be8f710d and d86d86639055bd23b3b824b437dcc16b706a02ac on top of the current 7_4_X HEAD?

**Comment by carolinecollard** [comment]
Hi Devdatta,

I don't know what you would like to change in the BTagAnalyzerMacros directory.
But I start also to be afraid by the number of lines which were changed.
Are you sure you are starting from the last update of the code?
I made a lot of changes in the past in DrawCommPlot.C to simplify the understanding of the code.
Be sure that you are not applying change back.

If there are too many changes, please keep them in separate files (with boosted in the name).
As Dinko pointed it, the codes that you want to change are used by several other persons.

Cheers,
Caroline

Le 9 juin 2015 à 18:28, Dinko Ferencek a écrit :

Btw, I don't want to be a pest, but is it really necessary to have so many merge commits. In this way the commit history gets unnecessarily very complicated (see https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/network). How about just cherry-picking 425b44ahttps://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/commit/425b44a0b608b9aa3ba762c89d734c47be8f710d and d86d866https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/commit/d86d86639055bd23b3b824b437dcc16b706a02ac on top of the current 7_4_X HEAD?

**Comment by dmajumder** [comment]
I am closing this PR and make a new one just with the cfg file change. About plotting scripts, the number of lines changed is spurious, and only few modifications were made. It is just that the git diffs take all banck spaces and line shifts into account. If I may make a suggestion, I'd say we create a separate repo for plotting and validation.

**Comment by ferencek** [comment]
In principle I agree that the validation code would logically better fit into a separate repository. Should I maybe transfer https://github.com/ferencek/cms-BTagValidation to the cms-btv-pog group?

**Comment by ferencek** [comment]
OK, I have just transferred the repository.

**Comment by ghost** [comment]
@ferencek  sorry, I didn't mean to ignore your question, but I didn't receive the notification of the comment, I guess it happens when the PR gets closed. However, I would have answered yes.

**Comment by ferencek** [comment]
No worries. That was more a general question for everybody. In the end, I thought the answer was mostly obvious since the code was already used within the BTV POG so there is no need to keep it in my private area.

**Pull request closed without merging**
