### PR TITLE
Add DeepCSV into the default BTA production, add the uncorrected jet pt for future training

### PR DESCRIPTION
**Pull request by mverzett**
@ferencek can you check that the addition of DeepCSV does not mess with the fat jets? Otherwise you can suggest me what incantation should I run.

### CODE REVIEW

**Comment by ferencek** [comment]
@mverzett, sorry, I did not have time to do any tests. Although, I would say the burden of proving nothing got broken is on the developer :)

For fat jets it should be sufficient to run with `runFatJets=True runSubJets=True` before and after code changes and make sure the code runs and nothing that's not supposed has changed.

**Comment by mverzett** [comment]
@ferencek , totally agree on that :). 
Thanks for pointing me to the correct set of options to run a test. I will do it asap

**Comment by ghost** [comment]
@mverzett would you mind checking the merge-topic as well? Following the current instructions I have the impression that several non-needed packages are downloaded

**Comment by mverzett** [comment]
@imarches , indeed that is a known problem. Those packages are not needed but they depend on the packages changed. As @ferencek was suggesting in the last email merge-topic -u should do the trick but might crash something else. Given I cannot know if somebody will use other packages as well I preferred the safe way.

**Comment by ghost** [comment]
Thanks, I understand. Maybe we can provide both options with a warning in the recipe

**Pull request merged**
