### PR TITLE
Added C tag  variables to BTagAnalyzer 7_6_X

### PR DESCRIPTION
**Pull request by kovitang**
Added the C tag training variables to BTagAnalyzer, including soft lepton variables and boolean in config file to run C tag in parallel with standard B tag. 

@mverzett is interested in following this

### CODE REVIEW

**Comment by ferencek** [comment]
@kovitang, this PR cannot be merged. Please resolve the merge conflicts first.

**Comment by kovitang** [comment]
@ferencek, conflicts are resolved.

**Comment by ferencek** [comment]
A similar PR for the _8_0_X branch will be needed (I haven't checked if 7_6_X can be merged into 8_0_X but perhaps we don't want to do that anyways so a separate PR will be needed).

**Comment by ghost** [comment]
@kovitang could you kindly confirm if you will be able to look at the 80X PR?

**Comment by kovitang** [comment]
@imarches Yes, I will. As of now, I am busy with personal issue and C-Tag PAS.

**Comment by ghost** [comment]
Thanks for your availability. Let us know in case of issues

**Pull request merged**
