### PR TITLE
Updates from Daniel on PhaseII

### PR DESCRIPTION
**Pull request by smoortga**
Snippet from e-mail of Daniel on the 7th January:

"... the PhaseII geometry has to be explicit in runBTagAnalyzer_cfg.py
and the setting in PhaseII.py was wrong,
there is also a more recent JEC for PhaseII ..."

### CODE REVIEW

**Comment by rauser** [comment]
Hey, thanks a lot for implementing the updates! Have there been changes in `python/varGroups_cfi.py` and `test/runBTagAnalyzer_cfg.py`? The diff somehow doesn't seem to show them correctly

**Comment by smoortga** [comment]
@rauser Yes these files had some small changes, but indeed the diffs seem to be too large to show. Since I just copied the files from Daniel, for some reason git sees it as a complete replacement even though most lines are still the same... I sent an e-mail to Daniel asking to verify if the correct changes were made before I merge this. 

Maybe it is due to some different line endings (as discussed here https://stackoverflow.com/questions/12876350/diff-returning-entire-file-for-identical-files) in the editor of Daniel... Don't know if it affects anything.

**Comment by rauser** [comment]
Ok, thanks a lot! Indeed it seems like an editor problem

**Comment by rauser** [comment]
@smoortga could you also forward the required changes in the 9_4_X_PhaseII branch (https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/tree/9_4_X_PhaseII)?

**Comment by smoortga** [comment]
@rauser sure! https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/118

**Pull request merged**
