### PR TITLE
More subjet variables

### PR DESCRIPTION
**Pull request by dmajumder**
Added more variables needed for subjet SF+systematics. 

Also added an example "common" dictionary (Moriond19Boosted.py) for boosted campaign. I think this list of groups should eventually include all boosted commissioning variables, i.e. Subjet CSV/ DeepCSV and DoubleB/ DeepDoubleB/ DeepDoubleC, which have similar event selections and use the BTagValidation code for commissioning.

### CODE REVIEW

**Comment by rauser** [comment]
@dmajumder is there a specific reason for running the tests with 1000 events, e.g. only a few in 1000 events have the required event shape? Otherwise could you decrease this number to 20 events, which is used for the other tests?
Cheers, Johann

**Comment by rauser** [comment]
@dmajumder , having merged PR https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/116 , can this PR be closed? Best, Johann

**Comment by dmajumder** [comment]
ok, i'm closing it.

**Comment by rauser** [comment]
Thanks!

**Pull request closed without merging**
