### PR TITLE
Small typo fix in DeepCSVCvsB discriminator

### PR DESCRIPTION
**Pull request by smoortga**

### CODE REVIEW

**Comment by smoortga** [comment]
hi @imarches @mverzett @JyothsnaKomaragiri ,

Could you please check and merge? it just fixes some naming conventions for the DeepCSVCvsL and CvsB discriminators

Cheers
Seth

**Comment by ghost** [comment]
Thanks. I let this to @mverzett as he's the Deep implementation expert

**Comment by mverzett** [comment]
@smoortga sorry for the lag in the reply, I am quite swamped as you know ;). The changes in interface/JetInfoBranches.h are definitely correct, most likely a copy-paste error. I am not sure though on the Cvs[LB], though, why did you switch them. Can you explain it? 
Thanks

P.S. aside that I think we should start using plain probc and proccc instead of these two since we have them.

**Comment by smoortga** [comment]
@mverzett 
No problem ;-) I discussed this issue with Markus and Caroline when making some ROCs and discriminators for the DeepCSV. It turned out that the current definition is counter intuitive when comparing to the c-tagger. You can convince yourself that for example in the DeepCSV CvsL definition, b-jets will be centered to the left, whereas they should actually be to the right of the c-jets. this new definition makes the distributions consistent with the c-tagger.

Perhaps you are right about using the probc and probcc, we should maybe at some point compare the ROCs by using these quantities to see if it indeed gives a similar or perhaps better result.

Cheers, Seth

**Comment by mverzett** [comment]
@smoortga OK, makes sense indeed, merging

**Pull request merged**
