### PR TITLE
Adding the DeepDoubleX and DeepBoostedJet (DeepAK8) commissioning variables v2

### PR DESCRIPTION
**Pull request by alefisico**
Adding the DeepDoubleX and DeepBoostedJet (DeepAK8) commissioning variables

### CODE REVIEW

**Comment by alefisico** [comment]
Hi all, is there something missing in this PR to get it merge?
btw, this PR needs CMSSW_9_4_13 since DeepDoubleX was merged in that release. 
thanks

**Comment by rauser** [comment]
First of all, thanks for this huge bunch of work :+1: The PR looks good to me. I have one or two minor questions:
- What is the reason for changing the defaults to use private JEC files and for changing the default MC input file in python/defaults/Moriond18.py?
- Is it required to run the integration tests with 1000 events?
- Did the other integration tests run without errors in CMSSW_9_4_13?

As @ferencek was requested for review, I would wait for his approval before merging it.
Cheers, Johann

**Comment by alefisico** [comment]
Hi @rauser 
here are my comments:
* We want to use PrivateJEC to use the latest JECs and, there is no big reason in the change of input. It is just that most of our selection is QCD. 
* No, no reason at all. You can pick a smaller number if needed. 
* Yes, all the test jobs finished without a problem.

Also, I added @ferencek as reviewer since he is working with us, and he knew what this PR is about. 
thanks for the help!

**Review by ferencek — COMMENTED** [review]
Fine with me to merge. I would just suggest to lower `maxEvents` in `test/run_tests.sh` to be in line with other unit tests.

**Pull request merged**
