### PR TITLE
Forward PR https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/116 to 10_2_X branch

### PR DESCRIPTION
**Pull request by rauser**
@alefisico could you have a look at this PR, as it is forwarding your work from PR https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/116 to the 10_2_X branch of the BTagAnalyzer (using CMSSW_10_2_11)? Due to the complexity I couldn't cherry-pick the commits, so I had to introduce the changes manually (hopefully without errors). The code compiles, the integration tests run successfully and the branches are being filled.
@emilbols could you have a look at https://github.com/rauser/cmssw/commits/PrunedTraining_NoPuppi_10_2_11 which is adapting your work for the pruned training without puppi to CMSSW_10_2_11?
@mverzett are you aware of any other risks when moving from CMSSW_10_2_7 to CMSSW_10_2_11?
Thanks,
Johann

### CODE REVIEW

**Comment by mverzett** [comment]
> @mverzett are you aware of any other risks when moving from CMSSW_10_2_7 to CMSSW_10_2_11?

@rauser not that I'm aware of

**Comment by rauser** [comment]
Ok, thanks!

**Comment by emilbols** [comment]
@rauser It looks alright

**Comment by rauser** [comment]
@emilbols thanks a lot for checking!

**Pull request merged**
