### PR TITLE
74x ttbardev

### PR DESCRIPTION
**Pull request by pfs**
Not sure if you prefer that I submit these changes to another branch.
It seems like it won't be a clean merge.

### CODE REVIEW

**Comment by ferencek** [comment]
There are now two other branches, `7_4_X_BoostedBTagCommissioning` and `7_5_X`, so @imarches and @dmajumder might want to comment on what would be the best way to proceed. In any case, this PR cannot be merged before the conflicts are resolved. Try rebasing `74x_ttbardev`.

**Comment by ghost** [comment]
Dear all,

future developments will happen continuing on the 75X branch. In order not to loose these important changes it would be nice to have this committed also there. This could represent a moderate work as only the changes to plugins/BTagAnalyzer.cc (about 20 lines) and test/runBTagAnalyzer_cfg.py (about 3 lines) should be applied to the new version of those files. This would represent the only additional work wrt the present PR. As some work needs to be done, anyway, to solve the merge conflicts, maybe it would be worth trying, if @pfs agrees?

**Comment by ghost** [comment]
Concerning 7_4_X_BoostedBTagCommissioning I let @dmajumder comment, as he created the branch. It seems that the only difference wrt 74X are some specific settings in runBTagAnalyzer_cfg.py

https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/commit/4e9aac615dfafaec5a671e34c041ab417fc21b49

**Comment by ferencek** [comment]
My general inclination is to have fewer branches and more configurable options. This makes the code maintenance a lot easier. So if possible, I would suggest to drop the `7_4_X_BoostedBTagCommissioning` branch and add more configurable options to the `7_4_X` branch. Concerning this PR, once rebased, there is a good chance the same branch can be used to make PRs for both `7_4_X` and `7_5_X`.

**Comment by dmajumder** [comment]
I do not think we need to port this to  7_4_X_BoostedBTagCommissioning, all changes from this should anyway be propagated to the 7_4_X branch. If any of the new switches are missing I will port them to 7_4_X and delete this, until we need some parallel development again.

**Comment by pfs** [comment]
I'm closing the PR. Will rebase and do the necessary changes to solve the conflicts.
Thanks

**Comment by ferencek** [comment]
No need to close. Just rebase and (force) push to the same branch.

**Comment by pfs** [comment]
ok opening it again :)

**Comment by pfs** [comment]
Closing this one.
Supersed by https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/18

**Pull request closed without merging**
