### PR TITLE
Configurable output for BTagAnalyzer

### PR DESCRIPTION
**Pull request by rauser**
The new version of the BTagAnalyzer, making the output configurable via variable groups and detecting automatically which run options need to be set.

### CODE REVIEW

**Comment by mverzett** [comment]
@rauser  thanks for the PR. Just to be sure, did you run ```test/run_tests.sh```? I so I will go ahead and merge it.

**Comment by rauser** [comment]
Yes, I ran the tests (successfully). Cheers!

**Comment by jmduarte** [comment]
@rauser @mverzett will this be backported to 94X ? We're wondering because we plan to use the 94X version for a first round of deep double-b commissioning for 2017.

**Comment by rauser** [comment]
In principle this shouldn't be a problem although it may take some time, as I'm not sure whether cherry-picking the commits will work straight forward. I'll have a look into it and keep in touch

**Comment by jmduarte** [comment]
Thanks @rauser !

**Comment by rauser** [comment]
I integrated the changes, see PR https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/110 . The diff is basically the same as for the PR in the 10_1_X branch, but maybe @mverzett wants to have a look. If there are no complaints, I'll merge it beginning of next week. Cheers Johann

**Pull request merged**
