### PR TITLE
7 4 x

### PR DESCRIPTION
**Pull request by dmajumder**
Adding a few further variables present in BTagAnalyzerLite.

### CODE REVIEW

**Comment by ferencek** [comment]
I don't understand this PR. It just adds a bunch of code indentations and in fact removes the Jet_tau_dot variable which was recently added. Closing.

**Comment by dmajumder** [comment]
It appeared that you do not want this (as well as several other variables) here.

**Comment by ferencek** [comment]
Devdatta, it's not that we don't want any new variables. The problem is that this PR appears to be mostly broken. I don't see any new variables and we certainly do not want to introduce unnecessary code indentation changes (cosmetic changes can eventually be done as a separate PR but are not really needed).

Can you point a single new variable that you are adding here that is not already included? Note that GitHub diff can sometime be broken or a bit hard to interpret.

**Comment by ferencek** [comment]
I think I understand now why the PR diff shows that you are adding new variables. You actually have duplicate lines of code in 

https://github.com/dmajumder/RecoBTag-PerformanceMeasurements/blob/7_4_X/interface/JetInfoBranches.h#L374-379 and https://github.com/dmajumder/RecoBTag-PerformanceMeasurements/blob/7_4_X/interface/JetInfoBranches.h#L383-388

https://github.com/dmajumder/RecoBTag-PerformanceMeasurements/blob/7_4_X/interface/JetInfoBranches.h#L653-655 and https://github.com/dmajumder/RecoBTag-PerformanceMeasurements/blob/7_4_X/interface/JetInfoBranches.h#L657-659

and a few other places. Also, excessive use of merge commits should be avoided as much as possible since it leads to very complicated commit histories which are hard to understand and can lead to incorrect/broken PR diffs.

**Pull request closed without merging**
