### PR TITLE
First Negative and Positive Ctag in BTagAnalyzer

### PR DESCRIPTION
**Pull request by kovitang**
The negative and positive Ctags are added to BTagAnalyzer

@mverzett is interested in following this

### CODE REVIEW

**Comment by ghost** [comment]
@kovitang thanks for this. As mentioned in the latest mail from Petra, though the SFl measurements will likely not go into the 76X PAS, it would still be nice to test them in 76X, so I would suggest to have this in 76X, as well. Thanks.

**Comment by mverzett** [comment]
For the record, this PR has to work together with a CMSSW PR that Keng will make asap (it is already ready) that introduces the taggers there too (and cleans a bit the code).

**Comment by ghost** [comment]
Could you kindly add the merge-topic with the PR branch to the instructions readme? So that the 80X works. If this has a longer time scale I would suggest to revert the merge of the PR until it is ready, to keep the 80X recipe functional.

**Comment by mverzett** [comment]
Done in #27

**Comment by ghost** [comment]
@mverzett thanks a lot! I will test it right now

**Pull request merged**
